#! /bin/sh

# Run monitor script here
if [[ "$( connected-DVI-monitors )" = DVI* ]]; then
    sleep 3 && init-DL-monitor &&  
    if [[ $( xsetwacom list devices ) ]]; then
        init-wacom
    fi
else
    echo null
fi &&
pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap is &
nitrogen --force-setter=xinerama --restore &
albert &
picom & 
$HOME/.config/polybar/launch.sh


bspc monitor eDP1 -d I II III IV V VI VII VIII
bspc config border_width         2
bspc config window_gap          10
bspc config focused_border_color "#CFFF9C"
bspc config split_ratio          0.63
bspc config borderless_monocle   true
bspc config gapless_monocle      true
