#! /bin/sh

# Run monitor script here
if [[ "$( connected-DVI-monitors )" = DVI* ]]; then
    ( init-DL-monitor && sleep 5 && nitrogen --force-setter=xinerama --restore ) &
    if [[ $( xsetwacom list devices ) ]]; then
        init-wacom
    fi
fi &
pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap is &
nitrogen --force-setter=xinerama --restore &
albert &
picom &

if [[ "$( pidof redshift )" = "" ]]; then
    /usr/lib/geoclue-2.0/demos/agent &
    redshift &
fi &

bspc monitor eDP1 -d I II III IV V VI &
if [[ "$( connected-DVI-monitors )" = DVI* ]]; then
    ( bspc monitor $( connected-DVI-monitors ) -d VII VIII IX X && \
        nitrogen --force-setter=xinerama --restore )
fi & $HOME/.config/polybar/launch.sh

bspc rule -a albert focus=on
bspc config border_width            2
bspc config window_gap              10
bspc config top_padding             10
bspc config focused_border_color    "#CFFF9C"
bspc config split_ratio             0.63
bspc config gapless_monocle         true
