#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

setxkbmap is &
nitrogen --restore &
picom &
albert &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config focused_border_color "#F0941F"
#:bspc config top_padding 	40

bspc config split_ratio          0.63
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
